### PR TITLE
Cleanup PR of func outputs(initialState: Self, inputEvents...

### PR DESCRIPTION
**Pull request by mdellagi77**
Hey guys. 

I just created a preparing PR for future pull requests with which I am aiming at making the 
`private static func outputs(initialState: Self, inputEvents: Signal<Event>, context: Context) -> EventsStatesAndEffects<Event, Self, Effect>` function more readable. 

I have made no logical changes in this request, just did some cleanup.

Namely:  
Extracting closures into functions that by there name convey there intention, moving sharing note to function description, Using type inference where possible, removing needless brackets, adding line breaks for legibilty

### CODE REVIEW

**Comment by ferranlala** [comment]
Thanks for the PR! Looks good, indeed everything is more clear.

Can you just put the comment you moved where it was before? It is a comment about an implementation detail.

**Comment by mdellagi77** [comment]
Sure

**Comment by mdellagi77** [comment]
Done

**Comment by ferranlala** [comment]
The comment is still not exactly on the same place where it was before, and the copied comment is still on the function signature 😁

**Comment by mdellagi77** [comment]
I left it in the function documentation on purpose. But I can completely revert it if you want…

**Comment by ferranlala** [comment]
Yes please remove it, the mentioned relay is local to the function, so it's not part of the function's interface.

**Comment by mdellagi77** [comment]
Done

**Comment by ferranlala** [comment]
Thanks, LGTM.

**Pull request merged**
